### ISSUE TITLE
API Improvement for Interoperabilty and Acceability to 3rd Party Programs or Platforms regarding UUID reuse

### ISSUE THREAD

**Issue by raederan** [FAU-LAP/NOMAD-CAMELS#113]
Dear NOMAD-CAMELS Developers,

In the current implementation of the API for executing protocols, it is not possible to pass an external UUID. For instance in run protocols api, see:
https://github.com/FAU-LAP/NOMAD-CAMELS/blob/985941a084b29688febd5529e8850527ee197069/nomad_camels/api/api.py#L213-L271

Same behaviour for the action queue api.

If a **_UUID_** has already been generated by a program or 3rd party platform, an _**optional**_ possibility to reuse it would be great. This also improves connectivity to external systems that have already assigned a UUID to a measurement. According to your contributor guides, I have forked your `development` branch and will open a pull request to offer a possible solution to this **_enhancement issue._**

Best regards
Andreas

**Comment by A-D-Fuchs** [comment]
Hey Andreas, 

thanks for bringing this issue up and fixing it right away.

That is a great improvement especially when using CAMELS with other software that might provide UUIDs. 

Best
Alex
