### ISSUE TITLE
fix local driver import names

### ISSUE THREAD

**Issue by MatPopp** [FAU-LAP/NOMAD-CAMELS#31]
Current state: 

folder name: 
nomad_camels_driver_driverTest

(1) not working file-names: 

driverTest.py
driverTest_ophyd.py

(2) working file-names: 

driverTest_ophyd.py
nomad_camels_driver_driverTest.py

according to documentation and site-packes (1) shoud be the working version

**Comment by Jo-Leh** [comment]
You are correct. This should be fixed in the latest version.

**Comment by A-D-Fuchs** [comment]
Is fixed in the newest version 0.1.21
