### ISSUE TITLE
Create Option and Functionality to save data during running measurment session

### ISSUE THREAD

**Issue by MatPopp** [FAU-LAP/NOMAD-CAMELS#36]
In order to save data when/if the program/PC crashes during measurements.

**Comment by Jo-Leh** [comment]
The data is saved live during the measurement, but only in .msgpack files.
The information is written into hdf5 (or others) after the measurement is finished / crashes.
For your case, we are planning to add a functionality to export the data from databroker later.

**Comment by Jo-Leh** [comment]
A quick solution is the following function:

```python
def export_run(filename, run_number=-1, plot_data=None, additional_data=None,
               session_name='', export_to_csv=False, export_to_json=False,
               catalog_name='CAMELS_CATALOG'):
    catalog = databroker.catalog[catalog_name]
    run = catalog[run_number]
    broker_to_NX([run], filename, plot_data, additional_data,
                 session_name, export_to_csv, export_to_json)
```

This could be added to `nomad_camels.utility.databroker_export`. The `run_number=-1` will choose the data from the newest run.

We will improve this function and add it to the UI in a future release.

**Comment by Jo-Leh** [comment]
A functionality to do this from the GUI will be in the next version
