### ISSUE TITLE
Debug window not showing up when no device is present

### ISSUE THREAD

**Issue by MatPopp** [FAU-LAP/NOMAD-CAMELS#38]
![grafik](https://github.com/FAU-LAP/NOMAD-CAMELS/assets/27500989/9b15177f-ad61-49bb-938c-5a34e265ad84)

When creating new device drivers no error Messages are shown. This makes debugging difficult, the only workaround now is to use a working dummy device get the console view for driver debugging.

![grafik](https://github.com/FAU-LAP/NOMAD-CAMELS/assets/27500989/96aa6359-d3d8-4e27-86c5-dc28317ee068)

the information marked in blue is needed when there is still no working device.

**Comment by Jo-Leh** [comment]
Thanks for pointing this out!
It is going to be fixed in the next version.
