### ISSUE TITLE
Preset cannot be loaded after renaming channels in device driver 

### ISSUE THREAD

**Issue by MatPopp** [FAU-LAP/NOMAD-CAMELS#39]
When changing for example a channel name within a device driver old presets cannot be loaded anymore => all configurations get lost when drivers are updated.
Suggestion: read options with try/ecxept statement and print warning if options from preset cannot be set.

![grafik](https://github.com/FAU-LAP/NOMAD-CAMELS/assets/27500989/a7bd3dab-58be-4c29-bb5f-bbf1361ac1f1)

**Comment by Jo-Leh** [comment]
This should now be different.
The preset should now still be loaded (displaying a Warning), but probably not all protocols will work, since the instrument will be missing.
Is this sufficient for your requirements?
