### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by NicolasCARPi** [FAU-LAP/NOMAD-CAMELS#60]
Hello,

While installing the software, I had a hard time figuring out how to start it.

The solution was found on another page. [The installation page](https://fau-lap.github.io/NOMAD-CAMELS/doc/installation/installation.html#camels-installation) only mentions installing it with pip.

I had to actively look for what to do to start it. It turns out that one needs to go into the ` venv/lib/python3.11/site-packages/nomad_camels` and execute `python CAMELS_start.py`.

This is really surprising (to me at least). Never once I saw a package asking me to actually dwelve into the guts of the install path to start the thingy.

I suggest adding a `console_script`, see: https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point

Such that this would work:

~~~bash
pip install nomad-camels
nomad-camels
# GUI appears
~~~

**Comment by NicolasCARPi** [comment]
Forgot to mention: https://github.com/openjournals/joss-reviews/issues/6371

**Comment by Jo-Leh** [comment]
This is a good point, thank you for the suggestion. It is included in the newest release and will be added to the documentation soon.

**Comment by A-D-Fuchs** [comment]
This is fixed in the most recent update (1.0.0) and was added to the [documentation](https://fau-lap.github.io/NOMAD-CAMELS/doc/installation/installation.html).

**Comment by NicolasCARPi** [comment]
Indeed, great!
