### ISSUE TITLE
Incorrect user data directory

### ISSUE THREAD

**Issue by NicolasCARPi** [FAU-LAP/NOMAD-CAMELS#62]
Hello,

Running the software created a folder `NOMAD_CAMELS_data` in my `$HOME`. :angry: 

Applications **must not** create random folders in the `$HOME`, but respect XDG Base Directory Specification: https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html

Ideally, the software would ask where user data could be saved instead of assuming the location.

review: https://github.com/openjournals/joss-reviews/issues/6371

**Comment by Jo-Leh** [comment]
Sorry for cluttering your ```$HOME```.
We will add a pop-up during the first start-up to the next version.
In the meantime you can change the directory in the settings menu. I hope this serves as a solution.

**Comment by NicolasCARPi** [comment]
> We will add a pop-up during the first start-up to the next version.

Yes, with default path suggesting `~/.config/nomad-camels` (keep it lowercase).

> In the meantime you can change the directory in the settings menu

I see. 

~~Two~~Three other things:

1. you have some hardcoded paths in your source code:

![2024-02-20-195132_908x482_scrot](https://github.com/FAU-LAP/NOMAD-CAMELS/assets/3043706/af257cc3-bb61-4465-9376-2c0def46d4f6)

2. Please add a "Quit" button to the "File" menu ;)

3. It might be good to address this ASAP: `nomad-camels/venv/lib/python3.11/site-packages/nomad_camels/CAMELS_start.py:107 DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466`

**Comment by Jo-Leh** [comment]
I am actually not sure about ```~/.config/nomad-camels```. This path is where the measured data should be saved. Would the user actually look for the data there? I was thinking about ```~/.local/share/nomad_camels_data``` would this make sense? I am not too familiar with Linux, so I am quite unsure about what good paths are.

1.) Thanks for pointing it out, this is fixed together with #66 
2.) This is going to be added in the next version 
3.) What would you suggest to do? In the linked issue there are some good reasons against pyarrow, so we discussed some possible options:
- We just keep everything as is, until pandas 3.0 launches, then pyarrow will come with the dependencies of pandas
- We add pyarrow to our requirements although we do not actually need it and it increases the size of the software, to remove the warning
- We keep pandas below 2.2.0, all features we needed so far are included, and the warning dissappears as well. But this might cause some issues in the future with other packages relying on pandas

**Comment by Jo-Leh** [comment]
Yes, exactly.
Both paths will be asked in the next version, the folder None should then be moved to a path that the user specifies.

**Comment by NicolasCARPi** [comment]
Trying the `development` branch now. It asks for folders on start. Nice job! :)

Another issue:

When trying to export to csv/json by selecting Tools > Export, the file browser should start in the data folder instead of the folder where CAMELS was started from.


Talking about this UI:
![2024-02-29-225946_627x360_scrot](https://github.com/FAU-LAP/NOMAD-CAMELS/assets/3043706/4d58d388-751f-440f-a75a-e33dde18f259)

Then, after clicking export, you don't know where the files end up. It turns out they appear in the `$HOME`. It would be better to ask for a folder here too.

**Comment by Jo-Leh** [comment]
The files were supposed to appear in the same directory as the hdf5 file. This should now be the case, additionally one can select the path if the files should go somewhere else.
