### ISSUE TITLE
Missing CONTRIBUTING.md

### ISSUE THREAD

**Issue by NicolasCARPi** [FAU-LAP/NOMAD-CAMELS#70]
It is essential to have a CONTRIBUTING.md file so potential contributers can have a single source of information for specificities to this repo (such as targeting the `development` branch).

It can also set ground rules.

https://github.com/openjournals/joss-reviews/issues/6371

**Comment by A-D-Fuchs** [comment]
Added the CONTRIBUTION .md file in 9c8a7619a54de583817d65b47fd086d5736967eb and updated the [documentation website](https://fau-lap.github.io/NOMAD-CAMELS/doc/contribute/general_process.html#) for contributing. The .md file simply links to the documentation page. @NicolasCARPi is this okay?
